name:             hspec-smallcheck
version:          0.5.2
license:          MIT
license-file:     LICENSE
copyright:        (c) 2013-2018 Simon Hengel
maintainer:       Simon Hengel <sol@typeful.net>
build-type:       Simple
category:         Testing
bug-reports:      https://github.com/hspec/hspec-smallcheck/issues
homepage:         http://hspec.github.io/
synopsis:         SmallCheck support for the Hspec testing framework
description:      SmallCheck support for the Hspec testing framework

github: hspec/hspec-smallcheck

ghc-options: -Wall

dependencies:
  - base >= 4.5.0.0 && < 5
  - hspec-core >= 2.10.0
  - smallcheck >= 1.1
  - call-stack
  - HUnit

library:
  exposed-modules: Test.Hspec.SmallCheck
  source-dirs: src

tests:
  spec:
    build-tools: hspec-discover
    source-dirs:
      - src
      - test
    main: Spec.hs
    dependencies:
      - hspec
      - QuickCheck
      - base-orphans
  example:
    source-dirs: example
    main: Spec.hs
    dependencies:
      - hspec
      - hspec-smallcheck
